### ISSUE TITLE
'create-react-class' not found

### ISSUE THREAD

**Issue by siddhant91** [leandrowd/react-responsive-carousel#109]
ERROR in ./~/react-responsive-carousel/lib/components/Carousel.js
Module not found: Error: Can't resolve 'create-react-class' in 'C:\Users\SWadher                                                                                            a\Documents\Footlocker\KFL\fl-inc-ui\node_modules\react-responsive-carousel\lib\                                                                                            components'
 @ ./~/react-responsive-carousel/lib/components/Carousel.js 8:23-52
 @ ./~/react-responsive-carousel/lib/index.js
 @ ./app/components/kids/common/Header/Header.jsx
 @ ./app/controllers/kids/global.jsx

ERROR in ./~/react-responsive-carousel/lib/components/Thumbs.js
Module not found: Error: Can't resolve 'create-react-class' in 'C:\Users\SWadher                                                                                            a\Documents\Footlocker\KFL\fl-inc-ui\node_modules\react-responsive-carousel\lib\                                                                                            components'
 @ ./~/react-responsive-carousel/lib/components/Thumbs.js 6:23-52

Cannot resolve this issue .

Can you please check and provide a solution

**Comment by leandrowd** [comment]
The fix was published to npm. Please get the latest version: `3.1.10` and let me know how it goes.

**Comment by siddhant91** [comment]
Thanks for quick reply , but i am using the latest release of package 
"react-responsive-carousel": "^3.1.9".

Is there anything that i am missing here  ? 

I just want to make a text carousel and not an image though .

**Comment by leandrowd** [comment]
Change your version to 3.1.10 and run npm install again. It should solve
the issue.

On 25 Apr. 2017 2:46 am, "siddhant91" <notifications@github.com> wrote:

Thanks for quick reply , but i am using the latest release of package
"react-responsive-carousel": "^3.1.9".

Is there anything that i am missing here ?

I just want to make a text carousel and not an image though .

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/leandrowd/react-responsive-carousel/issues/109#issuecomment-296738226>,
or mute the thread
