### ISSUE TITLE
Is it possible to reduce the slide amount when changing the width?

### ISSUE THREAD

**Issue by danvernon** [leandrowd/react-responsive-carousel#197]
I have changed the width in CSS to 260px
![screen shot 2017-11-24 at 10 04 33](https://user-images.githubusercontent.com/428197/33205457-e6442ef2-d0fe-11e7-97fb-42bdf2982b3c.png)

One slide rotation takes me off the screen and another makes it blank
![screen shot 2017-11-24 at 10 04 38](https://user-images.githubusercontent.com/428197/33205456-e62f482a-d0fe-11e7-9759-f5d7dcd98a93.png)

**Comment by leandrowd** [comment]
It's not supported at the moment. Happy to accept pull requests though ;)

**Comment by jackpilowsky** [comment]
I ran into this same issue and looked into adding a pull request, but it would require major changes to the lib files and the documentation. instead, I went through a more hacky approach: I used a 1x1 transparent .png for the image (image tag is required for react-responsive-carousel to work) and set the real image as a background cover image. 

2 caveats: 

1) You can't use thumbs. 
2) By necessity, part of the image will get cut off because of different aspect ratios. So, all the important content of the images should be near the center of the image. 

`constructImageSlide(asset, index){
    const styles = {
      div: {
        backgroundImage: 'url(/img/'+asset.link+')',
        backgroundPosition: 'center',
        backgroundSize: 'cover',
        cursor: 'pointer'
      },
      img: {
        width: '100%', 
        height: 300 
      }
    }
    return(
      <div key={index} style={styles.div} onClick={this.handleClick.bind(this, index)} >
          <img style={styles.img} src="/img/1x1.png" role="presentation" />
      </div>
    )
}`

**Comment by mohamadmek** [comment]
?
