### ISSUE TITLE
Animation customization

### ISSUE THREAD

**Issue by olytv** [leandrowd/react-responsive-carousel#255]
Are there any ways to customize animation? For example, if I want to "fade" animation. Thanks!

**Comment by prkirby** [comment]
Hey @leandrowd I'd be open to taking this one on, its a feature I need for a client. Just submit a PR from a fork?

**Comment by leandrowd** [comment]
Yes,  please do.  I'm a bit time poor ATM so  can't commit on timelines but will answer your as soon as I can.

**Comment by prkirby** [comment]
@leandrowd I spent some time tonight exploring the repo and figuring out how everything runs. From what I'm seeing, it looks like it would be a bit of a messy PR to just layer a custom animation handler on top of what currently exists, as the rendered position of the list seems to be derived from side effects of a few different function calls. Let me know if I'm way off on that. 

Would you be interested in me seeing if I could do a larger refactor, and try to decouple the animation handler / behavior from the actual input and data handling of the Carousel? Create an api that allows users to take the updated state of the Carousel, and return styles for specific items based on that? I was thinking something that let you return a dictionary for the list styles, selectedItem styles, and previousItem styles. Things like fade would be simple, but you could get pretty creative with it I feel. It would also have to expose the swipe behaviors to be able to animate from that as well, so I'd have to look into that.

Of course I would rework the current slide transition to work with that api, which would be a good example of an advanced animation handler haha.

Asking before I dig in, because it'll be a bit of a project and I want to make sure thats something you'd want for the repo.

**Comment by leandrowd** [comment]
Hey @prkirby, I think the community would love that, it has been requested a few times already. I can support you on getting that through but you will need to be able to move mostly by yourself due to restrict time available. If you are ok with that, please go ahead.

**Comment by prkirby** [comment]
@leandrowd Sounds good, will do! I've got some time open, so it will be a fun build. I should be good to handle on my own, I'll just ping here with q's. Do you mind if I add some docblocs to functions as part of the PR?

**Comment by leandrowd** [comment]
No, go ahead with the doc blocks :)
