### ISSUE TITLE
setting height to 100% does not adjust to 100% of parent's height and returning null creates black screen

### ISSUE THREAD

**Issue by DexiongYung** [leandrowd/react-responsive-carousel#265]
I set the height of the carousel to 100% and it doesn't go to 100% of the parent height, in fact it doesn't adjust at all, but if I set it in pixels it resize. Also I had this function that returns a div if a state is true and returns nothing otherwise. So it creates another carousel item if the state is true and false other, if the state is true it returns a page as expected, but if it is false carousel reads the null and returns just a black page.

**Comment by leandrowd** [comment]
Hi @DexiongYung, can you reproduce your issue using https://codesandbox.io/s/lp602ljjj7 ?

**Comment by laneysmith** [comment]
@leandrowd I think they're referring to how the Carousel breaks if you pass in `{null}` as one of the Carousel children, or if you pass `<div>{null}</div>` as one of the Carousel children it will render but display black instead of an image, and the thumbnails, control dots, and item counts will be out of sync. Example: https://codesandbox.io/s/y3yjvyw04x

One option would be to "sanitize" the items passed into the Carousel by filtering out invalid elements, unless you want the burden to be on the user to ensure all their items are valid. What do you think about filtering `this.props.children` for valid elements immediately, storing on Carousel state, and then referring to that everywhere we use the children?

**Comment by leandrowd** [comment]
I believe it would be better to sanitize before passing to the carousel but I'm open to different approaches. If you want to create a PR with what you have in mind...

**Comment by hatsuo** [comment]
@leandrowd what about the first question here about filling the container's height? (like in #150)

You can currently do this by messing with the styles:

#### React src ...
```js
<Carousel
  className="carousel-wrapper"
  showThumbs={false}
  ...
/>
````

#### ... + overrides.css
```css
.carousel-wrapper,
.carousel,
.carousel > .slider-wrapper,
.carousel > .slider-wrapper > .slider {
  height: 100%;
}
```

Here is an example on CodeSandbox: https://codesandbox.io/s/9jl6lyxok4

But I guess this may be likely to break in future updates.
Is it likely that there will be a prop for this?

**Comment by leandrowd** [comment]
I'd be happy to accept a PR introducing this behaviour...

**Comment by hxtruong6** [comment]
> I'd be happy to accept a PR introducing this behaviour...

Did you update the method to change Height of image? A props value ??
