### ISSUE TITLE
first and last array elemts duplicate when real dom created

### ISSUE THREAD

**Issue by benajbenaj** [leandrowd/react-responsive-carousel#395]
infiniteLoop create duplicate li tags

**Comment by apoorva-shah** [comment]
Hello @benajbenaj 

Do you know fix for this issue? You closed this issue, so I thought you may know the fix.

If you know how to avoid duplicate html then please help.

Thanks

**Comment by benajbenaj** [comment]
Hey @apoorva-shah 

I do not even know, i just closed it than cause this was my first issue and i did not actually know how is it going exactly, i changed to another type of carousel and after i closed it. I am sorry to cannot help you.

**Comment by bunge12** [comment]
Hey @benajbenaj, what other slider did you use that does not have this issue? Thanks in advance!

**Comment by benajbenaj** [comment]
Hey @bunge12, sorry for the late answer, unfortunately i really do not know what was that exactly but i think most of these kinda carousels can be handle this, but yes i also know can do this but theirs are not solid as this.

**Comment by lucasbasquerotto** [comment]
I was subscribed to this issue for years, but no solution was implemented, and the duplicated items were creating problems with the gallery that shows when clicking the image to expand (the first and last items were shown twice while navigating the gallery due to the duplication of the elements in the carousel).

For anyone that wants a solution for this, I created a custom component that do not add nor remove elements:

```ts
import { css } from '@emotion/react';
import React from 'react';
import { Carousel } from 'react-responsive-carousel';
import 'react-responsive-carousel/lib/styles/carousel.min.css'; // requires a loader

const arrowCss = css`
	outline: 0;
	opacity: 0.4;
	filter: alpha(opacity= 40);
	z-index: 2;
	cursor: pointer;
	background: none;
	border: 0;
	font-size: 32px;
	transition: all 0.25s ease-in;
	position: absolute;
	top: 20px;
	color: #fff;
	margin-top: 0;
	padding: 5px;
	font-size: 26px;
	top: 0;
	bottom: 0;

	:before {
		content: '';
		border-top: 8px solid rgba(0, 0, 0, 0);
		border-bottom: 8px solid rgba(0, 0, 0, 0);
		margin: 0 5px;
		display: inline-block;
	}

	:hover {
		opacity: 1;
		background: rgba(0, 0, 0, 0.2);
	}
`;

const arrowPrevCss = css`
	${arrowCss}

	left: 0;

	:before {
		border-right: 8px solid #fff;
	}
`;

const arrowNextCss = css`
	${arrowCss}

	right: 0;

	:before {
		border-left: 8px solid #fff;
	}
`;

export interface MainCarouselProps {
	interval?: number;
	children: React.ReactNode[] | undefined;
}

const notEmpty = <TValue,>(value: TValue | null | undefined): value is TValue =>
	value !== null && value !== undefined;

const MainCarousel: React.FC<MainCarouselProps> = ({ interval, children }) => {
	const items = children?.filter(notEmpty);
	const amount = items?.length ?? 0;
	const multiple = amount > 1;
	const [selectedItem, setSelectedItem] = React.useState(0);
	const [hover, setHover] = React.useState(false);
	React.useEffect(() => {
		if (multiple && !hover) {
			const timer = setInterval(() => {
				setSelectedItem((prev) => (prev + 1) % (amount ?? 1));
			}, interval || 3000);
			return () => clearInterval(timer);
		}
	}, [amount, multiple, interval, hover]);

	return (
		<div
			onMouseEnter={() => setHover(true)}
			onMouseLeave={() => setHover(false)}
		>
			<Carousel
				showThumbs={false}
				selectedItem={selectedItem}
				interval={interval}
				showArrows={multiple}
				showIndicators={multiple}
				stopOnHover
				showStatus={false}
				onChange={(index) => setSelectedItem(index)}
				renderArrowPrev={(onClick, hasPrev, label) => (
					<button
						type="button"
						css={arrowPrevCss}
						onClick={hasPrev ? onClick : () => setSelectedItem(amount - 1)}
						aria-label={label}
					/>
				)}
				renderArrowNext={(onClick, hasNext, label) => (
					<button
						type="button"
						css={arrowNextCss}
						onClick={hasNext ? onClick : () => setSelectedItem(0)}
						aria-label={label}
					/>
				)}
			>
				{items?.map((child, idx) => <div key={idx}>{child}</div>)}
			</Carousel>
		</div>
	);
};

export default MainCarousel;
```

I implemented the `autoPlay` behaviour myself to return to the first item after reaching the last item. I had to include the `previous` and `next` buttons because the default buttons do not show when you are in the first and the last items, respectively (I used the same css rules for these buttons as the default buttons of this library, so no difference should be visible).

You can use the component as is (just copy & paste) in your project (there's no dependency aside from `react-responsive-carousel` and `emotion-css`). You can adapt the css to any other css solution you use in your project with minor changes if you do not use `emotion`.
