### ISSUE TITLE
Lighthouse Accessibility issue: Lists do not contain only <li> elements...

### ISSUE THREAD

**Issue by turnerhayes** [leandrowd/react-responsive-carousel#399]
Lighthouse audit results in accessibility issue for the control dots:

![lighthouse_error_react-responsive-carousel](https://user-images.githubusercontent.com/6371670/74598248-200cab00-5023-11ea-8706-56edff342bf0.png)

Replicated in this sandbox:
https://codesandbox.io/s/react-responsive-carousel-lighthouse-audit-issue-0kxyl

When the audit is finished, it seems to correctly contain only `<li>` elements, so my guess is that, at some point during rendering there's some invalid element, but it's fixed by the time I inspect the DOM.

**Comment by FedeBev** [comment]
Hi there,
what about this?

In my opinion it would be better using div elements instead of ul/li. Since you give the ability do customize the indicator would be easier for us to have a div as father, currently we must return a `li` element and it could be a bit tricky.

If this suggestion is welcome I can take care of it.

**Comment by olaf89** [comment]
I have the same problem
