### ISSUE TITLE
Vertical thumbs

### ISSUE THREAD

**Issue by hazzyeer** [leandrowd/react-responsive-carousel#500]
Hello,
I would like to know if there is a way to do the thumbs in a vertical direction (left) instead of the default direction (horizontal).

**Comment by jangian** [comment]
I'd love to know this too

**Comment by kevinwaelkens** [comment]
For anyone who still needs this, I just wanted this as well and I did the following:

Add to the css class `.thumbs` (which is the <ul> container for the thumbs) the following css:
```css
    display: flex;
    flex-direction: column;
```

And make sure to use my fork `@instak/react-responsive-carousel` on npm (or fork it yourself and publish) because on that version I got rid of the thumbs animation when selecting a new item from the Carousel. Otherwise the `translation3d()` moves the thumbs out of view. I might still look into just being able to add a boolean `verticalThumbs` which then takes in account the vertical `translation3d()` and create a PR onto the repo, but for now this should fix your problem.
