### ISSUE TITLE
Responsiveness breaks when parent has `display: flex`

### ISSUE THREAD

**Issue by Tobbe** [leandrowd/react-responsive-carousel#512]
It's all in the title pretty much :)  

Here's a demo: https://codesandbox.io/s/morning-thunder-hcdl5

Make the preview smaller and pretty soon you'll see the carousel stop being responsive and instead causing a horizontal scrollbar.

Is this something that should be fixed in this component, and/or is there a way I can work around it in my own code? (While still keeping `display: flex` of course)

Here's a screenshot. That horizontal scrollbar should not be there, there is plenty of room left for the carousel to shrink to fit.

![image](https://user-images.githubusercontent.com/30793/95018874-8c93f300-0662-11eb-980c-785c5a5b8665.png)

**Comment by Tobbe** [comment]
For that perticular example, what you can do is wrap the `<Carousel>` in `<div style={{ width: '100%' }}></div>` and it will work. But that breaks pretty quickly when the carousel isn't the full width of the page, like if you have a side bar or something.

I have another example here https://codesandbox.io/s/funny-zhukovsky-rt0m0 with a sidebar that's also broken. But see what happens when you remove `infiniteLoop`, then it displays properly!

So something breaks in some width calculation when `infiniteLoop` is enabled.

**Comment by ishields** [comment]
@Tobbe did you ever figure out a resolution for this?  I'm using the carousel inside a bootstrap 4 row/col and it seems to break the draggability.

**Comment by Tobbe** [comment]
@ishields No, unfortunately not 🙁  Still waiting for a fix

**Comment by leandrowd** [comment]
Feel free to contribute the fix, unfortunately, I don't have time to fix it myself...

**Comment by Tobbe** [comment]
> Feel free to contribute the fix, unfortunately, I don't have time to fix it myself...

Do you have any idea where the bug might be? Any pointers to help me or anyone else get started on fixing it?

**Comment by renancleyson-dev** [comment]
The problem is that at some point the carousel as a flex item will shrink to its minimum content size, which is the carousel items content without any free space, so adding a lot of items will make the carousel larger, and eventually, it will break the responsiveness. This explains why adding the ```infiniteLoop``` flag breaks the carousel since it renders clones of the last and first item inside the carousel.

The solution is changing the minimum width to 0 instead of the minimum content size in the outer div of the component. Here's an example of how you can do it: https://codesandbox.io/s/sleepy-greider-64ed2?file=/src/index.css

**Comment by Tobbe** [comment]
That `min-width` fix works great! Thank you <3

**Comment by Tobbe** [comment]
Still having problems with a flexlayout with a sidebar though :( 

https://codesandbox.io/s/falling-currying-29tq3

The carousel is way too wide

**Comment by renancleyson-dev** [comment]
You nested a flex container inside another flex container in your example. It will work properly if you remove the `div` that is wrapping the `Carousel` component or the one that is wrapping the sidebar and carousel, but if you want it as it is in your example, then you are handling the same problem of the issue. So you need to set `min-width` to some value rather than `auto` in the inner flex container.
