### ISSUE TITLE
Loop is not working when you gives selectedItem

### ISSUE THREAD

**Issue by maxizhukov** [leandrowd/react-responsive-carousel#520]
I have 2 slides first is autoplay and I am using state for that to have current slide
`<Carousel`
`infiniteLoop`
`onChange = {this.handleSliderChanges}`
`statusFormatter={(current) => `Current slide: ${current}`}`

`export class LoginPage extends Component<IPassword> {`
`state: IPassword = {`
`currentSlide: 0,`
`handleSliderChanges = (selectedIndex: number) => {`
`this.setState({`
`currentSlide: selectedIndex`
`})`

`<Carousel`
`infiniteLoop`
`selectedItem = {this.state.currentSlide}`

And when it need to change from last slide to first it gooing directly left and slide all slides up first not like a loop (Needs to go right and showing first slide)

**Comment by renancleyson-dev** [comment]
I am not sure if I understand your code, but it seems to me that you want the selected item of two carousels to be in sync.

This library has the limitation of providing an uncontrolled component (uses internal state instead of receive data through props), so trying to use ```selectedItem``` prop as a state can lead to some bad and buggy behaviors, as pointed in #531.

Since the carousel handles the behavior you want internally, I tried to create an example that uses the second carousel ref to handle the changes on the first carousel: https://codesandbox.io/s/loop-is-not-working-when-you-gives-selecteditem-forked-ewiuc. But since the ```selectedItem``` state of both carousels aren't from the same source, I don't think any solution will be perfect.
