### ISSUE TITLE
How to prevent open link when user dragging and ends dragging element?

### ISSUE THREAD

**Issue by KirillioClockwork** [leandrowd/react-responsive-carousel#527]
I need to prevent open link when the user dragging and ends dragging the element
How can I do this?
Example:
```javascript
import React from "react";
import { Carousel } from "react-responsive-carousel";

export default () => {
  return (
    <Carousel useKeyboardArrows={true}
    showStatus={false}
    showThumbs={false}
    emulateTouch={true}>
      <div>
        <a href="http://www.github.com" target="_blank">
          <div>
            <img src="http://lorempixel.com/output/cats-q-c-640-480-1.jpg" />
          </div>
        </a>
        <p className="legend">Legend 1</p>
      </div>
      <div>
        <a href="http://www.github.com" target="_blank">
          <div>
            <img src="http://lorempixel.com/output/cats-q-c-640-480-1.jpg" />
          </div>
        </a>
        <p className="legend">Legend 1</p>
      </div>
    </Carousel>
  );
};
```

**Comment by AndreiPisica** [comment]
@KirillioClockwork 
I found a workaround for this. Maybe you don't need it anymore. But for someone else who might look at this issue here is the workaround:
Define 3 functions based on the given events: 
1) - `   function swipeEnded(){
        console.log("swipe ended")
        setTimeout(() => {setSwipeAction(false)}, 300); 
    }`
2) `    function pictureClicked(){

        if(isSwiping === false){
            console.log("this is click event")
        }
    }
`
3)  `    function swipeStarted(){
        console.log("swipe started")
        setTimeout(() => {setSwipeAction(true)}, 100);
    }`

Link them to your carousel: 
` <Carousel showArrows={false} showThumbs={false} showStatus={false} emulateTouch={true} onSwipeEnd={swipeEnded} onSwipeStart={swipeStarted}  onClickItem={pictureClicked} className="carousel">`

And you should be good to go. It's not the ideal solution but until there is a fix on this I am satisfied with this outcome.
