### ISSUE TITLE
Carousel Thumbnail Height Problem

### ISSUE THREAD

**Issue by karianpour** [leandrowd/react-responsive-carousel#570]
If we specify width and height for the `img` element in carousel, the thumbnail becomes very heigh,

I added `height: auto;` [here](https://github.com/leandrowd/react-responsive-carousel/blob/6378163876ce3fa4c67a5ef7634eff542d2a6a51/src/components/_carousel.scss#L64) and the problem fixed.

```
            <Carousel className={classes.carousel}>
              {model.images?.map((image) => (
                <Box key={image.id} className={classes.imageBox}>
                  <img
                    src={image.url}
                    width={image.width}
                    height={image.height}
                  />
                  <ModelImageRemover image={image} />
                </Box>
              ))}
            </Carousel>

```

![image](https://user-images.githubusercontent.com/24288617/109388916-39775100-791f-11eb-8d35-2b5f1a97694b.png)

I use JSS so I fixed it with:

```
  carousel: {
    "& .carousel img": {
      height: "auto",
    },
  },
```

**Comment by renancleyson-dev** [comment]
The default thumbs render method gets the `img` element from each child of `children` prop to render the thumbnails. The problem is probably that the thumb images will have the same style props as the slide images. You can work around this by using the `renderThumbs` prop to customize how the thumbnails will render.

Feel free, though, to provide a PR to change the default `renderThumbs` prop with tests. I think that simply using [`React.cloneElement`](https://reactjs.org/docs/react-api.html#cloneelement) [on this line](https://github.com/leandrowd/react-responsive-carousel/blob/2185ddbfbe8c16838f8c253466e0a6538d6f8ff1/src/components/Carousel.tsx#L149) and overwrite the `style` and `className` props to `undefined` will do the trick.

**Comment by karianpour** [comment]
@renancleyson-dev  I already gave the work around, we just need a single line css `hight: auto;` I will prepare a PR.
