### ISSUE TITLE
Swipeable not working on mobile

### ISSUE THREAD

**Issue by abdullahe** [leandrowd/react-responsive-carousel#577]
Hi,

I'm using version 3.2.12 with Gatsby. Unfortunately I could not make swipeable work on mobile. Rarely it works only on first slide, and does nothing on other slides. Tested on mobile Safari and Chrome on an iPhone. ``emulateTouch`` works on desktop.

Here is the component:

```javascript
import React from "react";

// requires a loader
import { Carousel } from "react-responsive-carousel";

const settings = {
  showArrows: false,
  interval: 3500,
  dynamicHeight: false,
  stopOnHover: false,
  infiniteLoop: true,
  showStatus: false,
  transitionTime: 500,
  showThumbs: false,
  showIndicators: true,
  swipeable: true,
  emulateTouch: true,
  autoPlay: true,
};

const TestimonialsCarousel = ({ testimonials }, featured) => (
  <Carousel {...settings}>
    {testimonials
      .filter((item) => (item.featured || !featured) == true)
      .map((item) => (
        <div key={item.quote}>
          <div className="has-text-left has-text-white is-size-6 is-family-secondary px-xxs">
            <blockquote>{item.quote}</blockquote>
          </div>
          <div className="has-text-left has-text-white has-text-weight-medium testimonialauthor pt-small px-xxs">
            <p>—{item.author}</p>
          </div>
        </div>
      ))}
  </Carousel>
);

export default TestimonialsCarousel;
```

[Here is the link](https://condescending-mayer-da8ee7.netlify.app/awards-recognitions) to test. Please try to swipe "Quotes" section where testimonials are shown. 

I am stuck, and I don't prefer to switch back to react-slick which has its own problems. Any help is appreciated. Thanks.

**Comment by Fox4148** [comment]
I just tested and It works on my phone.

**Comment by abdullahe** [comment]
Thanks @Fox4148 . I am testing with iOS (14.4.1) on Safari and Chrome. It only works on 1st slide, can't swipe rest of them. :/

**Comment by Fox4148** [comment]
@abdullahe what you can try is inject your custom class and look at this doc: [Apple Docs](https://developer.apple.com/library/archive/documentation/InternetWeb/Conceptual/SafariVisualEffectsProgGuide/AnimatingCSSTransitions/AnimatingCSSTransitions.html)

**Comment by Fox4148** [comment]
@abdullahe after looking at the inspector, I've noticed that there isn't any transition css, maybe you are doing it via javascript? You could try this: [MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/transform)

**Comment by abdullahe** [comment]
@Fox4148 I included the plugin's css. Not sure if it uses transform (css) or js. I think it is weird that both carousels (quotes and recognition) is swipeable on only first slide.

**Comment by vaclav-stummer-ooo** [comment]
Is there any way how to swipe any item of the carousel. I am currently using disposition of 3 items on the page with prop `centerSlidePercentage={33.33}` and the only middle item is swipeable, which resulting in quite confusing UX.

**Comment by Finesse** [comment]
I have the same issue and I've found the reason for your and my case. When the second slide is active, the `ul.slider` element (that listens to the touch events) stays on the left. The blue highlight on the screenshot below is that element:

<img src="https://user-images.githubusercontent.com/9006227/123614321-90e2ea80-d847-11eb-88a1-0b62dc24ba8e.jpeg" width="225" /> ![Screen Shot 2021-06-28 at 19 29 31](https://user-images.githubusercontent.com/9006227/123614272-858fbf00-d847-11eb-80b1-bd1bba200092.png)

iOS Safari handles touch events only on the element itself and not on its children. Therefore, when you touch a slide, nothing happens. In fact, you can swipe from the second slide if you start swiping from the very left of the screen.

In order to fix it, you need to make the `ul.slider` element always stay on the screen. A way to do it is creating a very long `::before` block that stays under every slide:

```css
/* Add this CSS to your website */
.slider {
  position: relative;
}
.slider::before {
  content: '';
  position: absolute;
  top: 0;
  left: 100%;
  width: 100000%;
  height: 100%;
}
```

For some reason Safari watches touch events on the `::before` block and not on the child elements. Newertheless, it works.

**Comment by abdullahe** [comment]
Thank you @Finesse 

I will update as soon as I try your solution. Cheers.

**Comment by abdullahe** [comment]
@Finesse Thanks for the solution. It is working now! It is not related to this problem, but when the site is opened, it jumps to section with the slider (quotes). Any idea why might that be?


If anyone is having the same issue, be sure to clear website data of Safari from iOS settings.

**Comment by peacemaker123456** [comment]
@Finesse very smart

**Comment by lamb0tiana** [comment]
Face on the same issue,

set this preventMovementUntilSwipeScrollTolerance={true}



<br class="Apple-interchange-newline">

**Comment by schkolne** [comment]
beautiful solution thanks! make sure to also see this for getting vertical swipe working correctly on iOS https://github.com/leandrowd/react-responsive-carousel/issues/469
