### ISSUE TITLE
Unexpected behaviour of CSS in child component

### ISSUE THREAD

**Issue by iamshouvikmitra** [leandrowd/react-responsive-carousel#587]
The `transform: translate .. ` property in the `<ul class="slider animated">` prevent child components position:fixed to take effect.

As discussed [here](https://achrafkassioui.com/blog/position-fixed-and-CSS-transforms/#:~:text=An%20HTML%20element%20with%20position,ancestors%20to%20recover%20fixed%20positioning) would be great if we could remove the transform property after the transition ends

**Comment by iamshouvikmitra** [comment]
My use case is such that I have a few buttons inside the carousel items which trigger a modal, which in turn has position: fixed

Currently, I am trying to do a workaround as such 
```
<Carousel
      onClickItem={async (item, e) => {
        if (carousel) {
          let x = document.querySelector(".slider.animated");
          x.style = "transform: none";
        }
      }}
    >
      {widgets}
    </Carousel>
```

Is there a more graceful way to achieve the results?

**Comment by yasserzakyw** [comment]
Have the same issue! 
I am using some `draggable` cards as the carousel items, but I face the same problem since dragged card gets `position: fixed` once dragging starts, which conflicts with transform style given to it's parent (Carousel).

@iamshouvikmitra  I tried the same workaround, but it just scrolls back to the first carousel item, which is visually annoying to the user. Especially of the carousel has so many items.

**Comment by shaunstoltz** [comment]
Only first shows... then this...translate3d(-1300%, 0px, 0px)

-1300% ???? no idea....
